# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitsocial" do
  version "0.17.2"

  on_macos do
    on_intel do
      sha256 "2155e5b288a3dadb71b73561775a63e92867d0fe142866171bd1c448c846fe04"
      url "https://github.com/gitsocial-org/gitsocial/releases/download/v#{version}/gitsocial_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "70130253346189a913e87763d05ea2121df14f8324c3a34c52feff528a652de6"
      url "https://github.com/gitsocial-org/gitsocial/releases/download/v#{version}/gitsocial_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "57bf40772f65abda512be56c760063aa97672526fc5e677505e57a5b52a85bed"
      url "https://github.com/gitsocial-org/gitsocial/releases/download/v#{version}/gitsocial_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9e0e3de20e6757aed6b2d27fadf8fc05c22d7354584e41e85d10df5f3cbdbc43"
      url "https://github.com/gitsocial-org/gitsocial/releases/download/v#{version}/gitsocial_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gitsocial"
  desc "Git-native collaboration — posts, issues, PRs, releases, all in your repo"
  homepage "https://github.com/gitsocial-org/gitsocial"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitsocial"

  # No zap stanza required

end
