# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitsocial" do
  version "0.10.1"

  on_macos do
    on_intel do
      sha256 "c023a069dff52a348b21f290e29755766f24d9d9c6e16bef1b1bb640b3c24e72"
      url "https://github.com/gitsocial-org/gitsocial/releases/download/v#{version}/gitsocial_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c7f07429dbd6a40ef73034e30f333785ad9cf6d49f53ca859009e55a7bc1fcb4"
      url "https://github.com/gitsocial-org/gitsocial/releases/download/v#{version}/gitsocial_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "47191e277c86520edf669d3c734016bd8ee788aeaa0b7137139d08d8df1332c8"
      url "https://github.com/gitsocial-org/gitsocial/releases/download/v#{version}/gitsocial_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "30324771766d8c5c19cddc81cdb6570a2688e3110b604a59a2ce93b8accdc8f6"
      url "https://github.com/gitsocial-org/gitsocial/releases/download/v#{version}/gitsocial_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gitsocial"
  desc "Git-native collaboration — posts, issues, PRs, releases, all in your repo"
  homepage "https://github.com/gitsocial-org/gitsocial"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitsocial"

  # No zap stanza required

end
