# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitsocial" do
  version "0.23.0"

  on_macos do
    on_arm do
      sha256 "d5b107635f760e3cb9b74cf3cb413c46f04cae2b211498442f8d23e267bdd916"
      url "https://github.com/gitsocial-org/gitsocial/releases/download/v#{version}/gitsocial_#{version}_darwin_arm64.zip"
    end
    on_intel do
      sha256 "080f63edc619e5a258ac7d3d2b5920f5be6e1195adcaeffbd6ce1ef047bf5e49"
      url "https://github.com/gitsocial-org/gitsocial/releases/download/v#{version}/gitsocial_#{version}_darwin_amd64.zip"
    end
  end
  on_linux do
    on_arm do
      sha256 "532bee7d0fbc1a0c011976957d1ede250a0cb10da67665e8b46af068178baba1"
      url "https://github.com/gitsocial-org/gitsocial/releases/download/v#{version}/gitsocial_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "59709c7bff4d9fd2672481fd1bee9a2c02a29db6013f32998685a2a0e499d6e8"
      url "https://github.com/gitsocial-org/gitsocial/releases/download/v#{version}/gitsocial_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gitsocial"
  desc "Git-native collaboration — posts, issues, PRs, releases, all in your repo"
  homepage "https://gitsocial.org"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitsocial"

  # No zap stanza required
end
